#!/bin/bash
echo "Fluorine setup is starting..."
doas setup-xorg-base
doas apk add build-base
doas apk add wmctrl lxappearance --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing/
doas apk add dialog bash git rsync make font-cantarell autoconf ttf-freefont polkit xorg-server xinit xrdb tumbler xwallpaper lxterminal thunar jgmenu openbox tint2 gtk+3.0-dev automake intltool gcc
cd ~
clear
curl -LO https://github.com/stevenhoneyman/l3afpad/archive/refs/heads/master.zip
unzip master.zip
cd l3afpad-master
exec ./autogen.sh
exec ./configure
make
doas make install-strip
cd ~
git clone https://github.com/lawl/opensnap
cd opensnap
make
doas make install
cd ~
git clone https://github.com/vinceliuice/Qogir-icon-theme
mkdir -p ~/.local/share/icons; ./Qogir-icon-theme/install.sh -d ~/.local/share/icons -c all
mkdir .themes
mkdir ~/Desktop
mkdir ~/Documents
mkdir ~/Downloads
mkdir ~/Music
mkdir ~/Pictures
mkdir ~/Videos
cd ~
git clone -b Material-Black-Colors-Desktop https://github.com/rtlewis1/GTK.git
cp -R GTK/* ~/.themes/
git clone https://github.com/4194304/fluorine
rsync -av fluorine/ ~
curl -LO https://github.com/manu-mannattil/adwaita-cursors/releases/download/v1.2/adwaita-cursors.tar.gz
tar xvzf adwaita-cursors.tar.gz
mkdir -p ~/.icons/default
mv adwaita-cursors/Adwaita/cursors ~/.icons/default
rm -rf fluorine Qogir-icon-theme GTK screenshot.png LICENSE README.md fluorine-settings adwaita-cursors
chmod -R +x ~/.fluorine
cp ~/.local/share/icons/Qogir/scalable/apps/file-manager.svg ~/.local/share/icons/Qogir/scalable/apps/org.xfce.thunar.svg
cp ~/.local/share/icons/Qogir/scalable/apps/org.xfce.terminal.svg ~/.local/share/icons/Qogir/scalable/apps/lxterminal.svg
sed -i "s/fluorine/$USER/g" ~/.config/gtk-3.0/bookmarks
mkdir -p ~/.config/l3afpad
doas addgroup $USER input
doas addgroup $USER video
bash ~/.fluorine/setup/dialog.sh
