#!/usr/bin/bash
sudo pacman -S dialog --noconfirm
: ${DIALOG_CANCEL=1}
tmp_file=$(tempfile 2>/dev/null) || tmp_file=/tmp/test$$
trap "rm -f $tmp_file" 0 1 2 5 15
dialog --title "Fluorine Setup" --clear --yesno \
	"Welcome to Fluorine Setup. \n
	\n
	If you would like to install the \n
	Fluorine desktop, select yes. \n
	If you would like to abort, select no." 10 50 2> $tmp_file
return_value=$?
case $return_value in
  $DIALOG_CANCEL)
	dialog --title "Fluorine Setup" --clear --msgbox \
	"Setup was aborted." 10 50
	clear
	exit
esac
sudo pacman -S rsync bc xorg-xrandr git wmctrl dialog lxappearance-obconf lxterminal xorg-xrdb tint2 openbox jgmenu xwallpaper xorg-xinit thunar tumbler cantarell-fonts obconf xorg-server gnu-free-fonts polkit l3afpad --noconfirm
cd ~
clear
git clone https://github.com/vinceliuice/Qogir-icon-theme
mkdir -p ~/.local/share/icons; ./Qogir-icon-theme/install.sh -d ~/.local/share/icons -c all
mkdir .themes
mkdir ~/Desktop
mkdir ~/Documents
mkdir ~/Downloads
mkdir ~/Music
mkdir ~/Pictures
mkdir ~/Videos
git clone https://github.com/lawl/opensnap.git
cd opensnap
make
sudo make install
cd ~
git clone -b Material-Black-Colors-Desktop https://github.com/rtlewis1/GTK.git
cp -R GTK/* ~/.themes/
git clone https://github.com/4194304/fluorine
rsync -av fluorine/ ~
curl -LO https://github.com/manu-mannattil/adwaita-cursors/releases/download/v1.2/adwaita-cursors.tar.gz
tar xvzf adwaita-cursors.tar.gz
mkdir -p ~/.icons/default
mv adwaita-cursors/Adwaita/cursors ~/.icons/default
rm -rf fluorine Qogir-icon-theme GTK screenshot.png LICENSE README.md fluorine-settings adwaita-cursors adwaita-cursors.tar.gz opensnap
chmod -R +x ~/.fluorine
cp ~/.local/share/icons/Qogir/scalable/apps/file-manager.svg ~/.local/share/icons/Qogir/scalable/apps/org.xfce.thunar.svg
cp ~/.local/share/icons/Qogir/scalable/apps/org.xfce.terminal.svg ~/.local/share/icons/Qogir/scalable/apps/lxterminal.svg
sed -i "s/fluorine/$USER/g" ~/.config/gtk-3.0/bookmarks
mkdir -p ~/.config/l3afpad
exec ~/.fluorine/setup/dialog.sh
