#!/usr/bin/bash
sudo echo "Starting update setup..."
: ${DIALOG_CANCEL=1}
tmp_file=$(tempfile 2>/dev/null) || tmp_file=/tmp/test$$
trap "rm -f $tmp_file" 0 1 2 5 15
dialog --title "Fluorine Setup" --clear --yesno \
	"Would you like to update Fluorine?" 5 50 2> $tmp_file
return_value=$?
case $return_value in
  $DIALOG_CANCEL)
	clear
	exit
esac

sudo pacman -Sy xorg-xdpyinfo xorg-xrandr bc rsync git wmctrl dialog lxappearance-obconf lxterminal xorg-xrdb tint2 openbox jgmenu xwallpaper xorg-xinit thunar tumbler cantarell-fonts obconf xorg-server gnu-free-fonts polkit l3afpad --noconfirm
clear
git clone https://github.com/4194304/fluorine
rm -rf ~/fluorine/.config/
rm ~/fluorine/.xinitrc
rm ~/fluorine/.Xresources
rsync -av fluorine/ ~
curl -LO https://github.com/manu-mannattil/adwaita-cursors/releases/download/v1.2/adwaita-cursors.tar.gz
tar xvzf adwaita-cursors.tar.gz
mkdir -p ~/.icons/default
mv adwaita-cursors/Adwaita/cursors ~/.icons/default
rm -rf fluorine Qogir-icon-theme GTK screenshot.png LICENSE README.md fluorine-settings adwaita-cursors adwaita-cursors.tar.gz opensnap
chmod -R +x ~/.fluorine

clear &> /dev/stdout
