#!/usr/bin/bash
: ${DIALOG_CANCEL=1}
tmp_file=$(tempfile 2>/dev/null) || tmp_file=/tmp/test$$
trap "rm -f $tmp_file" 0 1 2 5 15
dialog --title "Fluorine Setup" --clear --yesno \
	"Would you like to update Fluorine?" 10 50 2> $tmp_file
return_value=$?
case $return_value in
  $DIALOG_CANCEL)
	clear
	exit
esac

sudo pacman -S rsync git wmctrl dialog lxappearance-obconf lxterminal xorg-xrdb tint2 openbox jgmenu xwallpaper xorg-xinit thunar tumbler cantarell-fonts obconf xorg-server gnu-free-fonts polkit l3afpad --noconfirm 2>&1 | dialog --title "Fluorine Setup" --progressbox "Please wait while packages update..." 30 50
clear
dialog --title "Updating..." --gauge \
	"Please wait while Fluorine updates. \n
Do not power off or restart your computer." 10 50 0 & {
cd ~
clear
} &> /dev/null

dialog --clear --title "Fluorine Setup" --gauge \
	"Please wait while Fluorine updates. \n
Do not power off or restart your computer." 10 50 66 & {
git clone https://github.com/4194304/fluorine-desktop
rsync -av fluorine-desktop/ ~
curl -LO https://github.com/manu-mannattil/adwaita-cursors/releases/download/v1.2/adwaita-cursors.tar.gz
tar xvzf adwaita-cursors.tar.gz
mkdir -p ~/.icons/default
mv adwaita-cursors/Adwaita/cursors ~/.icons/default
} &> /dev/null

dialog --clear --title "Fluorine Setup" --gauge \
	"Please wait while the setup process completes. \n
\n
While setup is running, please do not power off your computer or cancel setup." 10 50 83 & {
rm -rf fluorine-desktop Qogir-icon-theme GTK screenshot.png LICENSE README.md fluorine-settings adwaita-cursors
chmod -R +x ~/.fluorine
} &> /dev/null

clear
